SELECT
  CODEDESCRIPTION.KCODEDESCID,
  CODEDESCRIPTION.CODELONGDESCRIPTION AS LANK,
  CODEDESCRIPTION.CODESHORTDESCRIPTION AS KORT,
  CODEDESCRIPTION1.CODELONGDESCRIPTION AS LONG,
  CODEDESCRIPTION1.CODESHORTDESCRIPTION AS SHORT
FROM
  CODEDESCRIPTION
  INNER JOIN CODEDESCRIPTION CODEDESCRIPTION1 ON CODEDESCRIPTION1.KCODEDESCID = CODEDESCRIPTION.KCODEDESCID
WHERE
  CODEDESCRIPTION.KSYSTEMLANGUAGECODEID = 2 AND
  CODEDESCRIPTION1.KSYSTEMLANGUAGECODEID = 3
