SELECT
  RESIDENCE.KRESIDENCEID AS RESIDENCEID,
  RESIDENCENAME.NAME,
  RESIDENCE.FSITEORGUNITNUMBER AS CAMPUS,
  RESIDENCE.STARTDATE,
  RESIDENCE.ENDDATE,
  RESIDENCE.RESIDENCECAPACITY,
  X000_Codedescription.SHORT AS RESIDENCE_TYPE
FROM
  RESIDENCE
  LEFT JOIN RESIDENCENAME ON RESIDENCENAME.KRESIDENCEID = RESIDENCE.KRESIDENCEID
  LEFT JOIN X000_Codedescription ON X000_Codedescription.KCODEDESCID = RESIDENCE.FRESIDENCETYPECODEID
WHERE
  (RESIDENCENAME.KSYSTEMLANGUAGECODEID = 3 AND
  RESIDENCE.STARTDATE <= Date("2018-01-01") AND
  RESIDENCE.ENDDATE >= Date("2018-12-31")) OR
  (RESIDENCENAME.KSYSTEMLANGUAGECODEID = 3 AND
  RESIDENCE.ENDDATE >= Date("2018-01-01") AND
  RESIDENCE.ENDDATE <= Date("2018-12-31")) OR
  (RESIDENCENAME.KSYSTEMLANGUAGECODEID = 3 AND
  RESIDENCE.STARTDATE >= Date("2018-01-01") AND
  RESIDENCE.STARTDATE <= Date("2018-12-31"))
ORDER BY
  RESIDENCEID
