SELECT
  TRANSINST.FRESIDENCEID,
  X010_Active_residence.NAME,
  TRANSINST.FROOMTYPECODEID,
  X000_Codedescription.SHORT AS ROOM_TYPE,
  TRANSINST.STARTDATE,
  TRANSINST.ENDDATE,
  TRANSINST.AMOUNT,
  TRANSINST.DAILYRATE,
  TRANSINST.KTRANSINSTID
FROM
  TRANSINST
  LEFT JOIN X000_Codedescription ON X000_Codedescription.KCODEDESCID = TRANSINST.FROOMTYPECODEID
  INNER JOIN X010_Active_residence ON X010_Active_residence.RESIDENCEID = TRANSINST.FRESIDENCEID
WHERE
  (TRANSINST.STARTDATE >= Date("2018-01-01") AND
  TRANSINST.STARTDATE <= Date("2018-12-31")) OR
  (TRANSINST.ENDDATE >= Date("2018-01-01") AND
  TRANSINST.ENDDATE <= Date("2018-12-31")) OR
  (TRANSINST.STARTDATE <= Date("2018-01-01") AND
  TRANSINST.ENDDATE >= Date("2018-12-31"))
