SELECT
  XXNWU_COI_DECLARATIONS.DECLARATION_ID,
  XXNWU_COI_DECLARATIONS.EMPLOYEE_NUMBER,
  XXNWU_COI_DECLARATIONS.DECLARATION_DATE,
  XXNWU_COI_DECLARATIONS.UNDERSTAND_POLICY_FLAG,
  XXNWU_COI_DECLARATIONS.INTEREST_TO_DECLARE_FLAG,
  XXNWU_COI_DECLARATIONS.FULL_DISCLOSURE_FLAG,
  HR_LOOKUPS.MEANING AS STATUS,
  XXNWU_COI_DECLARATIONS.LINE_MANAGER,
  XXNWU_COI_DECLARATIONS.REJECTION_REASON,
  XXNWU_COI_DECLARATIONS.CREATION_DATE,
  XXNWU_COI_DECLARATIONS.AUDIT_USER,
  XXNWU_COI_DECLARATIONS.LAST_UPDATE_DATE,
  XXNWU_COI_DECLARATIONS.LAST_UPDATED_BY,
  XXNWU_COI_DECLARATIONS.EXTERNAL_REFERENCE
FROM
  XXNWU_COI_DECLARATIONS
  LEFT JOIN HR_LOOKUPS ON HR_LOOKUPS.LOOKUP_CODE = XXNWU_COI_DECLARATIONS.STATUS_ID AND HR_LOOKUPS.LOOKUP_TYPE =
    "NWU_COI_STATUS"
WHERE
  HR_LOOKUPS.START_DATE_ACTIVE <= XXNWU_COI_DECLARATIONS.DECLARATION_DATE AND
  HR_LOOKUPS.END_DATE_ACTIVE >= XXNWU_COI_DECLARATIONS.DECLARATION_DATE
ORDER BY
  XXNWU_COI_DECLARATIONS.EMPLOYEE_NUMBER,
  XXNWU_COI_DECLARATIONS.DECLARATION_DATE
