Select
    KREW_DOC_HDR_T.DOC_HDR_ID,
    KREW_DOC_HDR_T.DOC_TYP_ID,
    KREW_DOC_TYP_T.DOC_TYP_NM,
    KREW_DOC_TYP_T.LBL
From
    KREW_DOC_HDR_T Inner Join
    KREW_DOC_TYP_T On KREW_DOC_TYP_T.DOC_TYP_ID = KREW_DOC_HDR_T.DOC_TYP_ID
