Select
    PDP_PMT_GRP_T_PREV.PMT_GRP_ID,
    PDP_PMT_GRP_T_PREV.PAYEE_ID,
    PDP_PMT_GRP_T_PREV.PMT_PAYEE_NM,
    X000_Vendor.PAYEE_NM,
    X000_Vendor.VNDR_NM,
    X000_Vendor.VNDR_URL_ADDR,
    X000_Vendor.VNDR_TAX_NBR,
    X000_Vendor.BNK_ACCT_NBR,
    PDP_PMT_GRP_T_PREV.PAYEE_ID_TYP_CD,
    X000_Vendor.PAYEE_TYP_DESC,
    PDP_PMT_GRP_T_PREV.DISB_NBR,
    PDP_PMT_GRP_T_PREV.DISB_TS,
    PDP_PMT_GRP_T_PREV.PMT_DT,
    PDP_PMT_GRP_T_PREV.PMT_STAT_CD,
    PDP_PMT_STAT_CD_T.PMT_STAT_CD_DESC,
    PDP_PMT_DTL_T.CUST_PMT_DOC_NBR,
    PDP_PMT_DTL_T.INV_NBR,
    PDP_PMT_DTL_T.REQS_NBR,
    PDP_PMT_DTL_T.PO_NBR,
    PDP_PMT_DTL_T.INV_DT,
    PDP_PMT_DTL_T.ORIG_INV_AMT,
    PDP_PMT_DTL_T.NET_PMT_AMT
From
    PDP_PMT_GRP_T_PREV Left Join
    X000_Vendor On Trim(X000_Vendor.PAYEE_ID_NBR) = Trim(PDP_PMT_GRP_T_PREV.PAYEE_ID)
            And Trim(X000_Vendor.PAYEE_ID_TYP_CD) = Trim(PDP_PMT_GRP_T_PREV.PAYEE_ID_TYP_CD) Left Join
    PDP_PMT_STAT_CD_T On PDP_PMT_STAT_CD_T.PMT_STAT_CD = PDP_PMT_GRP_T_PREV.PMT_STAT_CD Left Join
    PDP_PMT_DTL_T On PDP_PMT_DTL_T.PMT_GRP_ID = PDP_PMT_GRP_T_PREV.PMT_GRP_ID
