Select
    PUR_VNDR_ADDR_T.VNDR_HDR_GNRTD_ID,
    PUR_VNDR_ADDR_T.VNDR_DTL_ASND_ID,
    PUR_VNDR_ADDR_T.VNDR_ADDR_TYP_CD,
    PUR_VNDR_ADDR_T.VNDR_DFLT_ADDR_IND,
    Count(PUR_VNDR_ADDR_T.VNDR_LN1_ADDR) As Count_VNDR_LN1_ADDR
From
    PUR_VNDR_ADDR_T
Where
    PUR_VNDR_ADDR_T.VNDR_DFLT_ADDR_IND = 'Y'
Group By
    PUR_VNDR_ADDR_T.VNDR_HDR_GNRTD_ID,
    PUR_VNDR_ADDR_T.VNDR_DTL_ASND_ID,
    PUR_VNDR_ADDR_T.VNDR_ADDR_TYP_CD,
    PUR_VNDR_ADDR_T.VNDR_DFLT_ADDR_IND
