Select Distinct
    PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR As VENDOR_ID,
    STUD.BNK_ACCT_NBR As STUD_BANK,
    STUD.PAYEE_ID_TYP_CD As STUD_TYPE,
    VEND.BNK_ACCT_NBR As VEND_BANK,
    VEND.PAYEE_ID_TYP_CD As VEND_TYPE,
    EMPL.BNK_ACCT_NBR As EMPL_BANK,
    EMPL.PAYEE_ID_TYP_CD As EMPL_TYPE
From
    PDP_PAYEE_ACH_ACCT_T
    Left Join PDP_PAYEE_ACH_ACCT_T STUD On STUD.PAYEE_ID_NBR = PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR And STUD.PAYEE_ID_TYP_CD = 'S' And STUD.ROW_ACTV_IND = 'Y'
    Left Join PDP_PAYEE_ACH_ACCT_T VEND On VEND.PAYEE_ID_NBR = PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR And VEND.PAYEE_ID_TYP_CD = 'V' And VEND.ROW_ACTV_IND = 'Y'
    Left Join PDP_PAYEE_ACH_ACCT_T EMPL On EMPL.PAYEE_ID_NBR = PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR And EMPL.PAYEE_ID_TYP_CD = 'E' And EMPL.ROW_ACTV_IND = 'Y'
Where
    PDP_PAYEE_ACH_ACCT_T.ROW_ACTV_IND = 'Y'
