Select
    REP.PAYEE_TYPE,
    REP.PAYEE_TYP_DESC As PAYEE_TYPE_DESC,
    REP.PAYEE_OWNR_CD_CALC As OWNER_TYPE,
    REP.PAYEE_OWNR_DESC As OWNER_TYPE_DESC,
    REP.VENDOR_TYPE_CALC As VENDOR_TYPE,
    REP.DOC_TYPE,
    REP.DOC_LABEL As DOC_TYPE_DESC,
    Count(REP.EDOC) As TRAN_COUNT,
    Total(REP.NET_PMT_AMT) As TRAN_TOTAL
From
    X001aa_Report_payments REP
Group By
    REP.PAYEE_TYPE,
    REP.PAYEE_TYP_DESC,
    REP.PAYEE_OWNR_CD_CALC,
    REP.PAYEE_OWNR_DESC,
    REP.VENDOR_TYPE_CALC,
    REP.DOC_TYPE,
    REP.DOC_LABEL