Select
    PDP_PAYEE_ACH_ACCT_T.ACH_ACCT_GNRTD_ID,
    PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR,
    PDP_PAYEE_ACH_ACCT_T.BNK_ACCT_NBR,
    PUR_VNDR_HDR_T.VNDR_TAX_NBR,
    PDP_PAYEE_ACH_ACCT_T.ROW_ACTV_IND,
    PDP_PAYEE_ACH_ACCT_T.PAYEE_NM,
    PDP_PAYEE_ACH_ACCT_T.PAYEE_EMAIL_ADDR,
    PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_TYP_CD,
    PDP_PAYEE_TYP_T.PAYEE_TYP_DESC,
    PDP_PAYEE_TYP_T.ACH_ELGBL_IND,
    PDP_PAYEE_ACH_ACCT_T.ACH_TRANS_TYP,
    PDP_PAYEE_ACH_ACCT_T.BNK_ACCT_TYP_CD,
    PUR_VNDR_HDR_T.VNDR_HDR_GNRTD_ID,
    PUR_VNDR_HDR_T.VNDR_TYP_CD,
    PUR_VNDR_HDR_T.VNDR_TAX_TYP_CD,
    PUR_VNDR_HDR_T.VNDR_OWNR_CD,
    PUR_VNDR_HDR_T.VNDR_FRGN_IND,
    PUR_VNDR_DTL_T.VNDR_NM,
    PUR_VNDR_DTL_T.DOBJ_MAINT_CD_ACTV_IND,
    PUR_VNDR_DTL_T.VNDR_INACTV_REAS_CD,
    PUR_VNDR_DTL_T.VNDR_PMT_TERM_CD,
    PUR_VNDR_DTL_T.VNDR_SHP_TTL_CD,
    PUR_VNDR_DTL_T.VNDR_URL_ADDR,
    PUR_VNDR_DTL_T.VNDR_1ST_LST_NM_IND,
    PUR_VNDR_DTL_T.COLLECT_TAX_IND,
    PUR_VNDR_DTL_T.VNDR_PARENT_IND,
    PUR_VNDR_DTL_T.VNDR_HDR_GNRTD_ID As VNDR_HDR_GNRTD_ID1,
    PUR_VNDR_DTL_T.VNDR_DTL_ASND_ID
From
    PDP_PAYEE_ACH_ACCT_T Left Join
    PDP_PAYEE_TYP_T On PDP_PAYEE_TYP_T.PAYEE_TYP_CD = PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_TYP_CD Left Join
    PUR_VNDR_HDR_T On PUR_VNDR_HDR_T.VNDR_HDR_GNRTD_ID = SubStr(PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR, 1, 8) Left Join
    PUR_VNDR_DTL_T On PUR_VNDR_DTL_T.VNDR_HDR_GNRTD_ID || '-' || PUR_VNDR_DTL_T.VNDR_DTL_ASND_ID =
            PDP_PAYEE_ACH_ACCT_T.PAYEE_ID_NBR
