SELECT
  GL_ENTRY_T_CURR.UNIV_FISCAL_YR,
  GL_ENTRY_T_CURR.UNIV_FISCAL_PRD_CD,
  GL_ENTRY_T_CURR.CALC_COST_STRING,
  X000_Account.ORG_NM,
  X000_Account.ACCOUNT_NM,
  CA_OBJECT_CODE_T.FIN_OBJ_CD_NM,
  GL_ENTRY_T_CURR.TRANSACTION_DT,
  GL_ENTRY_T_CURR.FDOC_NBR,
  GL_ENTRY_T_CURR.CALC_AMOUNT,
  GL_ENTRY_T_CURR.TRN_LDGR_ENTR_DESC,
  X000_Account.ACCT_TYP_NM,
  GL_ENTRY_T_CURR.TRN_POST_DT,
  GL_ENTRY_T_CURR."TIMESTAMP",
  GL_ENTRY_T_CURR.FIN_COA_CD,
  GL_ENTRY_T_CURR.ACCOUNT_NBR,
  GL_ENTRY_T_CURR.FIN_OBJECT_CD,
  GL_ENTRY_T_CURR.FIN_BALANCE_TYP_CD,
  GL_ENTRY_T_CURR.FIN_OBJ_TYP_CD,
  GL_ENTRY_T_CURR.FDOC_TYP_CD,
  GL_ENTRY_T_CURR.FS_ORIGIN_CD,
  FS_ORIGIN_CODE_T.FS_DATABASE_DESC,
  GL_ENTRY_T_CURR.TRN_ENTR_SEQ_NBR,
  GL_ENTRY_T_CURR.FDOC_REF_TYP_CD,
  GL_ENTRY_T_CURR.FS_REF_ORIGIN_CD,
  GL_ENTRY_T_CURR.FDOC_REF_NBR,
  GL_ENTRY_T_CURR.FDOC_REVERSAL_DT,
  GL_ENTRY_T_CURR.TRN_ENCUM_UPDT_CD
FROM
  GL_ENTRY_T_CURR
  LEFT JOIN X000_Account ON X000_Account.FIN_COA_CD = GL_ENTRY_T_CURR.FIN_COA_CD AND X000_Account.ACCOUNT_NBR =
    GL_ENTRY_T_CURR.ACCOUNT_NBR
  LEFT JOIN CA_OBJECT_CODE_T ON CA_OBJECT_CODE_T.UNIV_FISCAL_YR = GL_ENTRY_T_CURR.UNIV_FISCAL_YR AND
    CA_OBJECT_CODE_T.FIN_COA_CD = GL_ENTRY_T_CURR.FIN_COA_CD AND CA_OBJECT_CODE_T.FIN_OBJECT_CD =
    GL_ENTRY_T_CURR.FIN_OBJECT_CD
  LEFT JOIN FS_ORIGIN_CODE_T ON FS_ORIGIN_CODE_T.FS_ORIGIN_CD = GL_ENTRY_T_CURR.FS_ORIGIN_CD
ORDER BY
  GL_ENTRY_T_CURR.CALC_COST_STRING,
  GL_ENTRY_T_CURR.UNIV_FISCAL_PRD_CD
