Select
    CONT.VNDR_HDR_GNRTD_ID,
    CONT.VNDR_CNTCT_GNRTD_ID,
    CONT.VNDR_CNTCT_TYP_CD As CONTACT_TYPE,
    Trim(Upper(CONT.VNDR_CNTCT_NM)) As CONTACT,
    Trim(Upper(CONT.VNDR_ATTN_NM)) As ATTENTION,
    Lower(CONT.VNDR_CNTCT_EMAIL_ADDR) As EMAIL,
    PHON.VNDR_PHN_NBR As PHONE,
    MOBI.VNDR_PHN_NBR As MOBILE
From
    PUR_VNDR_CNTCT_T CONT Left Join
    PUR_VNDR_CNTCT_PHN_NBR_T PHON On PHON.VNDR_CNTCT_GNRTD_ID = CONT.VNDR_CNTCT_GNRTD_ID Left Join
    PUR_VNDR_CNTCT_PHN_NBR_T MOBI On MOBI.VNDR_CNTCT_GNRTD_ID = CONT.VNDR_CNTCT_GNRTD_ID
Where
    PHON.VNDR_PHN_TYP_CD = 'PH' And
    MOBI.VNDR_PHN_TYP_CD = 'MB'
Order By
    CONT.VNDR_HDR_GNRTD_ID,
    CONTACT_TYPE