Select
    PHON.VNDR_HDR_GNRTD_ID,
    PHON.VNDR_PHN_GNRTD_ID,
    LAND.VNDR_PHN_NBR As PHONE,
    MOBI.VNDR_PHN_NBR As MOBILE
From
    PUR_VNDR_PHN_NBR_T PHON Left Join
    PUR_VNDR_PHN_NBR_T LAND On LAND.VNDR_PHN_GNRTD_ID = PHON.VNDR_PHN_GNRTD_ID And LAND.VNDR_PHN_TYP_CD = 'PH' Left Join
    PUR_VNDR_PHN_NBR_T MOBI On MOBI.VNDR_PHN_GNRTD_ID = PHON.VNDR_PHN_GNRTD_ID And MOBI.VNDR_PHN_TYP_CD = 'MB'
Order By
    PHON.VNDR_HDR_GNRTD_ID