Select
    VEND.VNDR_ID As VENDOR_ID,
    PHON.PHONE,
    PHON.MOBILE,
    CONT.CONTACT,
    CONT.ATTENTION,
    CONT.EMAIL,
    CONT.PHONE As PHONEC,
    CONT.MOBILE As MOBILEC
From
    PUR_VNDR_DTL_T VEND Left Join
    X001af_vendor_phone PHON On PHON.VNDR_HDR_GNRTD_ID = VEND.VNDR_HDR_GNRTD_ID Inner Join
    X001ae_vendor_contact CONT On CONT.VNDR_HDR_GNRTD_ID = VEND.VNDR_HDR_GNRTD_ID