Select
    TRAN.STUDENT,
    Total(TRAN.AMOUNT) As FEE_BURS
From
    X000_Transaction TRAN
Where
    TRAN.TRANSCODE = '042' Or
    TRAN.TRANSCODE = '052' Or
    TRAN.TRANSCODE = '381' Or
    TRAN.TRANSCODE = '500'
Group By
    TRAN.STUDENT