Select
    STU.KSTUDBUSENTID,
    STU.PRESENT_CAT
From
    X000_Student STU Left Join
    X021ab_findings_list FIN On FIN.KSTUDBUSENTID = STU.KSTUDBUSENTID
            And FIN.QUALIFICATION = STU.QUALIFICATION
Where
    STU.PRESENT_CAT Like ('C%')