Select
    STUD.FQUALLEVELAPID,
    STUD.CAMPUS,
    STUD.QUALIFICATION,
    STUD.QUALIFICATION_NAME,
    Count(STUD.KSTUDBUSENTID) As COUNT_STUD,
    TRAN.TRAN_COUNT_ALL
From
    X000_Student STUD Left Join
    X020aa_Trans_feequal TRAN On TRAN.FQUALLEVELAPID = STUD.FQUALLEVELAPID
Where
    STUD.PRESENT_CAT Like ('C%')
Group By
    STUD.FQUALLEVELAPID,
    STUD.CAMPUS