Select
    x000s.KRELATIONSHIPTYPECODEID,
    x000s.REL_TYPE,
    Count(x000s.KSTUDBUSENTID) As Count_KSTUDBUSENTID
From
    X000_Student_relationship x000s
Group By
    x000s.KRELATIONSHIPTYPECODEID,
    x000s.REL_TYPE