SELECT
  PER_ALL_ASSIGNMENTS_F.ASSIGNMENT_ID AS ASS_ID,
  PER_ALL_ASSIGNMENTS_F.ASSIGNMENT_NUMBER,
  PER_ALL_ASSIGNMENTS_F.PERSON_ID,
  PER_ALL_ASSIGNMENTS_F.SUPERVISOR_ID,
  PER_ALL_ASSIGNMENTS_F.EMPLOYMENT_CATEGORY,
  PER_ALL_ASSIGNMENTS_F.PRIMARY_FLAG,
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_START_DATE,
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_END_DATE,
  PER_ALL_ASSIGNMENTS_F.PERIOD_OF_SERVICE_ID,
  X000_PER_PERIODS_OF_SERVICE.DATE_START AS SERVICE_DATE_START,
  X000_PER_PERIODS_OF_SERVICE.ACTUAL_TERMINATION_DATE AS SERVICE_DATE_ACTUAL_TERMINATION,
  X000_PER_PERIODS_OF_SERVICE.LAST_STANDARD_PROCESS_DATE AS SERVICE_DATE_STD_PROCESS,
  X000_PER_PERIODS_OF_SERVICE.FINAL_PROCESS_DATE AS SERVICE_FINAL_PROCESS,
  X000_PER_PERIODS_OF_SERVICE.LEAVING_REASON,
  X000_PER_PERIODS_OF_SERVICE.LEAVE_REASON_DESCRIP,
  PER_ALL_ASSIGNMENTS_F.GRADE_ID,
  X000_GRADES.GRADE,
  X000_GRADES.GRADE_NAME,
  PER_ALL_ASSIGNMENTS_F.POSITION_ID,
  X000_POSITIONS.POSITION,
  X000_POSITIONS.POSITION_NAME,
  X000_POSITIONS.ACAD_SUPP,
  PER_ALL_ASSIGNMENTS_F.JOB_ID,
  X000_JOBS.JOB_NAME,
  X000_JOBS.JOB_SEGMENT_NAME,
  PER_ALL_ASSIGNMENTS_F.ASSIGNMENT_STATUS_TYPE_ID,
  PER_ALL_ASSIGNMENTS_F.LOCATION_ID,
  HR_LOCATIONS_ALL.LOCATION_CODE,
  HR_LOCATIONS_ALL.DESCRIPTION AS LOCATION_DESCRIPTION,
  PER_ALL_ASSIGNMENTS_F.ORGANIZATION_ID,
  X000_ORGANIZATION.ORG_TYPE,
  X000_ORGANIZATION.ORG_TYPE_DESC,
  X000_ORGANIZATION.OE_CODE,
  X000_ORGANIZATION.ORG_NAME,
  PER_ALL_ASSIGNMENTS_F.ASS_ATTRIBUTE1 AS ASS_WEEK_LEN,
  PER_ALL_ASSIGNMENTS_F.ASS_ATTRIBUTE2,
  PER_ALL_ASSIGNMENTS_F.PEOPLE_GROUP_ID,
  PAY_PEOPLE_GROUPS.GROUP_NAME AS "LEAVE_CODE"
FROM
  PER_ALL_ASSIGNMENTS_F
  LEFT JOIN X000_PER_PERIODS_OF_SERVICE ON X000_PER_PERIODS_OF_SERVICE.PERIOD_OF_SERVICE_ID =
    PER_ALL_ASSIGNMENTS_F.PERIOD_OF_SERVICE_ID
  LEFT JOIN X000_GRADES ON X000_GRADES.GRADE_ID = PER_ALL_ASSIGNMENTS_F.GRADE_ID
  LEFT JOIN X000_POSITIONS ON X000_POSITIONS.POSITION_ID = PER_ALL_ASSIGNMENTS_F.POSITION_ID
  LEFT JOIN X000_JOBS ON X000_JOBS.JOB_ID = PER_ALL_ASSIGNMENTS_F.JOB_ID
  LEFT JOIN HR_LOCATIONS_ALL ON HR_LOCATIONS_ALL.LOCATION_ID = PER_ALL_ASSIGNMENTS_F.LOCATION_ID
  LEFT JOIN X000_ORGANIZATION ON X000_ORGANIZATION.ORGANIZATION_ID = PER_ALL_ASSIGNMENTS_F.ORGANIZATION_ID
  LEFT JOIN PAY_PEOPLE_GROUPS ON PAY_PEOPLE_GROUPS.PEOPLE_GROUP_ID = PER_ALL_ASSIGNMENTS_F.PEOPLE_GROUP_ID
WHERE
  (PER_ALL_ASSIGNMENTS_F.EFFECTIVE_END_DATE >= Date('2018-01-01') AND
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_END_DATE <= Date('2018-12-31')) OR
  (PER_ALL_ASSIGNMENTS_F.EFFECTIVE_START_DATE >= Date('2018-01-01') AND
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_START_DATE <= Date('2018-12-31')) OR
  (PER_ALL_ASSIGNMENTS_F.EFFECTIVE_END_DATE >= Date('2018-12-31') AND
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_START_DATE <= Date('2018-01-01'))
ORDER BY
  ASS_ID,
  PER_ALL_ASSIGNMENTS_F.EFFECTIVE_START_DATE DESC
