SELECT
  ALL_TAB_COLUMNS.TABLE_NAME,
  ALL_TAB_COLUMNS.COLUMN_ID,
  ALL_TAB_COLUMNS.COLUMN_NAME,
  ALL_TAB_COLUMNS.DATA_TYPE,
  ALL_TAB_COLUMNS.DATA_LENGTH,
  ALL_TAB_COLUMNS.DEFAULT_LENGTH,
  ALL_TAB_COLUMNS.OWNER,
  ALL_TAB_COLUMNS.NULLABLE,
  ALL_TAB_COLUMNS.DATA_DEFAULT,
  ALL_TABLES.NUM_ROWS
FROM
  ALL_TAB_COLUMNS
  LEFT JOIN ALL_TABLES ON ALL_TABLES.TABLE_NAME = ALL_TAB_COLUMNS.TABLE_NAME
ORDER BY
  ALL_TAB_COLUMNS.TABLE_NAME,
  ALL_TAB_COLUMNS.COLUMN_ID
