Select
    pay.RUN_RESULT_ID,
    pay.CLASSIFICATION_NAME,
    pay.ELEMENT_NAME,
    pay.REPORTING_NAME As PAYROLL_NAME,
    pay.EFFECTIVE_DATE,
    loc.DESCRIPTION As CAMPUS,
    org.DIVISION,
    org.FACULTY,
    org.ORG1_TYPE_DESC As ORGANIZATION_TYPE,
    org.ORG1_NAME As ORGANIZATION_NAME,
    loo.MEANING As ASS_CATEGORY,
    pay.POSITION_ID,
    pos.POSITION,
    pos.POSITION_NAME,
    pay.EMPLOYEE_CATEGORY As EMPLOYEE_CATEGORY_ASS,
    Case
        When pay.POSITION_ID = 0
        Then pay.EMPLOYEE_CATEGORY
        Else pos.ACAD_SUPP
    End As EMPLOYEE_CATEGORY,
    pay.ASSIGNMENT_ID,
    pay.PERSON_ID,
    pay.EMPLOYEE_NUMBER,
    pay.RESULT_VALUE As PAYROLL_VALUE
From
    PAYROLL_HISTORY_2022 pay Left Join
    HR_LOCATIONS_ALL loc On loc.LOCATION_ID = pay.LOCATION_ID Left Join
    X000_ORGANIZATION_STRUCT org On org.ORG1 = pay.ORGANIZATION_ID Left Join
    HR_LOOKUPS loo On loo.LOOKUP_CODE = pay.EMPLOYMENT_CATEGORY Left Join
    X000_POSITIONS pos On pos.POSITION_ID = pay.POSITION_ID
            And pay.EFFECTIVE_DATE Between pos.EFFECTIVE_START_DATE And pos.EFFECTIVE_END_DATE
Where
    loo.LOOKUP_TYPE = 'EMP_CAT'