Select
    PAYM.ASSIGNMENT_ID,
    PAYM.EFFECTIVE_START_DATE,
    PAYM.EFFECTIVE_END_DATE,
    PAYM.PERSONAL_PAYMENT_METHOD_ID,
    PAYM.BUSINESS_GROUP_ID,
    PAYM.ORG_PAYMENT_METHOD_ID,
    upper(PMET.ORG_PAYMENT_METHOD_NAME) As ORG_PAYMENT_METHOD_NAME,
    PAYM.PPM_INFORMATION_CATEGORY,
    PAYM.PPM_INFORMATION1,
    PAYM.CREATED_BY,
    PAYM.CREATION_DATE,
    PAYM.LAST_UPDATE_DATE,
    PAYM.LAST_UPDATED_BY,
    PAYM.EXTERNAL_ACCOUNT_ID,
    EXTA.TERRITORY_CODE,
    EXTA.SEGMENT1 As ACC_BRANCH,
    EXTA.SEGMENT2 As ACC_TYPE_CODE,
    Upper(HRTY.MEANING) As ACC_TYPE,
    EXTA.SEGMENT3 As ACC_NUMBER,
    EXTA.SEGMENT4 As ACC_HOLDER,
    EXTA.SEGMENT5 As ACC_UNKNOWN,
    EXTA.SEGMENT6 As ACC_RELATION_CODE,
    Upper(HRRE.MEANING) As ACC_RELATION
From
    PAY_PERSONAL_PAYMENT_METHODS_F PAYM Inner Join
    PAY_EXTERNAL_ACCOUNTS EXTA On EXTA.EXTERNAL_ACCOUNT_ID = PAYM.EXTERNAL_ACCOUNT_ID Left Join
    HR_LOOKUPS HRTY On HRTY.LOOKUP_CODE = EXTA.SEGMENT2
            And HRTY.LOOKUP_TYPE = 'ZA_ACCOUNT_TYPE' Left Join
    HR_LOOKUPS HRRE On HRRE.LOOKUP_CODE = EXTA.SEGMENT6
            And HRRE.LOOKUP_TYPE = 'ZA_ACCOUNT_HOLDER_RELATION' Left Join
    PAY_ORG_PAYMENT_METHODS_F PMET On PMET.ORG_PAYMENT_METHOD_ID = PAYM.ORG_PAYMENT_METHOD_ID
            And PAYM.EFFECTIVE_END_DATE Between PMET.EFFECTIVE_START_DATE And PMET.EFFECTIVE_END_DATE