Select
    X002_PEOPLE_PREV_YEAR.EMPLOYEE_NUMBER,
    X002_PEOPLE_PREV_YEAR.FULL_NAME,
    X002_PEOPLE_PREV_YEAR.ORG_NAME,
    X002_PEOPLE_PREV_YEAR.ASS_START,
    X002_PEOPLE_PREV_YEAR.ASS_END,
    X002_PEOPLE_PREV_YEAR.EMP_START,
    X002_PEOPLE_PREV_YEAR.EMP_END,
    X002_PEOPLE_PREV_YEAR.LEAVING_REASON,
    X002_PEOPLE_PREV_YEAR.LEAVE_REASON_DESCRIP
From
    X002_PEOPLE_PREV_YEAR
Where
    (X002_PEOPLE_PREV_YEAR.ORG_NAME Like ('%PEOPLE%') And
        X002_PEOPLE_PREV_YEAR.LEAVING_REASON <> "") Or
    (X002_PEOPLE_PREV_YEAR.ORG_NAME Like ('%P&C%') And
        X002_PEOPLE_PREV_YEAR.LEAVING_REASON <> "")
Order By
    X002_PEOPLE_PREV_YEAR.EMP_END,
    X002_PEOPLE_PREV_YEAR.EMP_START