Select
    X002_PEOPLE_CURR.ORG_NAME,
    X002_PEOPLE_CURR.POSITION_NAME,
    X002_PEOPLE_CURR.GRADE_CALC,
    Count(X002_PEOPLE_CURR.AGE) As Count_AGE
From
    X002_PEOPLE_CURR
Group By
    X002_PEOPLE_CURR.ORG_NAME,
    X002_PEOPLE_CURR.POSITION_NAME,
    X002_PEOPLE_CURR.GRADE_CALC