SELECT
  PER_ORG_STRUCTURE_ELEMENTS.ORGANIZATION_ID_CHILD,
  Total(PER_ORG_STRUCTURE_ELEMENTS.PROGRAM_APPLICATION_ID) AS Total_PROGRAM_APPLICATION_ID
FROM
  PER_ORG_STRUCTURE_ELEMENTS
WHERE
  PER_ORG_STRUCTURE_ELEMENTS.ORG_STRUCTURE_VERSION_ID = 61
GROUP BY
  PER_ORG_STRUCTURE_ELEMENTS.ORGANIZATION_ID_CHILD
