Select
    X000_GROUPINSURANCE_SPOUSE.ELEMENT_VALUE,
    Count(X000_GROUPINSURANCE_SPOUSE.EMPLOYEE_NUMBER) As Count_EMPLOYEE_NUMBER
From
    X000_GROUPINSURANCE_SPOUSE
Group By
    X000_GROUPINSURANCE_SPOUSE.ELEMENT_VALUE