Select
    paaf.ASSIGNMENT_NUMBER,
    paaf.ASSIGNMENT_ID,
    paaf.EFFECTIVE_START_DATE,
    paaf.EFFECTIVE_END_DATE,
    paaf.GRADE_ID,
    paaf.POSITION_ID,
    paaf.JOB_ID,
    peap.POSITION_DEFINITION_ID,
    pepd.START_DATE_ACTIVE,
    pepd.END_DATE_ACTIVE,
    pepd.SEGMENT4
From
    PER_ALL_ASSIGNMENTS_F paaf Left Join
    PER_ALL_POSITIONS peap On peap.POSITION_ID = paaf.POSITION_ID Left Join
    PER_POSITION_DEFINITIONS pepd On pepd.POSITION_DEFINITION_ID = peap.POSITION_DEFINITION_ID
Where
    paaf.ASSIGNMENT_NUMBER Like ("21484260%")
Order By
    paaf.EFFECTIVE_START_DATE