SELECT
  HR_ALL_ORGANIZATION_UNITS.ORGANIZATION_ID,
  HR_ALL_ORGANIZATION_UNITS.LOCATION_ID,
  HR_ALL_ORGANIZATION_UNITS.DATE_FROM,
  HR_ALL_ORGANIZATION_UNITS.DATE_TO,
  HR_ALL_ORGANIZATION_UNITS.TYPE AS ORG_TYPE,
  HR_ALL_ORGANIZATION_UNITS.ATTRIBUTE_CATEGORY AS ORG_TYPE_DESC,
  HR_ALL_ORGANIZATION_UNITS.ATTRIBUTE1,
  HR_ALL_ORGANIZATION_UNITS.ATTRIBUTE2 AS ORG_NAAM,
  HR_ALL_ORGANIZATION_UNITS.NAME AS OE_CODE,
  HR_ORGANIZATION_INFORMATION.ORG_INFORMATION1 AS ORG_NAME,
  HR_ALL_ORGANIZATION_UNITS.CREATION_DATE,
  HR_ALL_ORGANIZATION_UNITS.CREATED_BY,
  HR_ALL_ORGANIZATION_UNITS.LAST_UPDATE_DATE,
  HR_ALL_ORGANIZATION_UNITS.LAST_UPDATED_BY,
  HR_ALL_ORGANIZATION_UNITS.LAST_UPDATE_LOGIN,
  HR_ALL_ORGANIZATION_UNITS.BUSINESS_GROUP_ID,
  HR_ALL_ORGANIZATION_UNITS.COST_ALLOCATION_KEYFLEX_ID,
  HR_ALL_ORGANIZATION_UNITS.SOFT_CODING_KEYFLEX_ID
FROM
  HR_ALL_ORGANIZATION_UNITS
  LEFT JOIN HR_ORGANIZATION_INFORMATION ON HR_ORGANIZATION_INFORMATION.ORGANIZATION_ID = HR_ALL_ORGANIZATION_UNITS.ORGANIZATION_ID
    AND HR_ORGANIZATION_INFORMATION.ORG_INFORMATION_CONTEXT = 'NWU_ORG_INFO'
