SELECT
  PER_GRADES.GRADE_ID,
  PER_GRADES.DATE_FROM,
  PER_GRADES.DATE_TO,
  PER_GRADES.GRADE_DEFINITION_ID,
  PER_GRADE_DEFINITIONS.SEGMENT1 AS GRADE,
  PER_GRADES.NAME AS GRADE_COMB,
  PER_GRADES.CREATED_BY,
  PER_GRADES.CREATION_DATE,
  PER_GRADES.LAST_UPDATED_BY,
  PER_GRADES.LAST_UPDATE_LOGIN,
  PER_GRADES.SEQUENCE,
  PER_GRADE_DEFINITIONS.SEGMENT2 AS GRADE_SEGMENT,
  PER_GRADE_DEFINITIONS.ID_FLEX_NUM,
  PER_GRADES.BUSINESS_GROUP_ID,
  X000_OWN_HR_LOOKUPS.LOOKUP_DESCRIPTION
FROM
  PER_GRADES
  LEFT JOIN PER_GRADE_DEFINITIONS ON PER_GRADE_DEFINITIONS.GRADE_DEFINITION_ID = PER_GRADES.GRADE_DEFINITION_ID
  LEFT JOIN X000_OWN_HR_LOOKUPS ON X000_OWN_HR_LOOKUPS.LOOKUP_CODE = PER_GRADE_DEFINITIONS.SEGMENT1 AND
    X000_OWN_HR_LOOKUPS.LOOKUP = 'GRADE'
ORDER BY
  PER_GRADES.GRADE_ID
