SELECT
  X000_ORG_STRUCT_7.ORG_STRUCTURE_ELEMENT_ID,
  X000_ORG_STRUCT_7.BUSINESS_GROUP_ID,
  X000_ORG_STRUCT_7.ORG_STRUCTURE_VERSION_ID,
  X000_ORG_STRUCT_7.ORG1,
  ORG1.ORG_TYPE AS ORG1_TYPE,
  ORG1.ORG_TYPE_DESC AS ORG1_TYPE_DESC,
  ORG1.OE_CODE AS ORG1_OE_CODE,
  ORG1.ORG_NAME AS ORG1_NAME,
  ORG1.ORG_NAAM AS ORG1_NAAM,
  X000_ORG_STRUCT_7.ORG2,
  ORG2.ORG_TYPE AS ORG2_TYPE,
  ORG2.ORG_TYPE_DESC AS ORG2_TYPE_DESC,
  ORG2.OE_CODE AS ORG2_OE_CODE,
  ORG2.ORG_NAME AS ORG2_NAME,
  ORG2.ORG_NAAM AS ORG2_NAAM
FROM
  X000_ORG_STRUCT_7
  LEFT JOIN X000_ORGANIZATION ORG1 ON ORG1.ORGANIZATION_ID = X000_ORG_STRUCT_7.ORG1
  LEFT JOIN X000_ORGANIZATION ORG2 ON ORG2.ORGANIZATION_ID = X000_ORG_STRUCT_7.ORG2
