SELECT
  X002_PEOPLE_CURR.EMPLOYEE_NUMBER,
  X002_PEOPLE_CURR.PERSON_ID,
  X002_PEOPLE_CURR.DATE_EMP_LOOKUP,
  PER_PHONES.PHONE_ID,
  PER_PHONES.DATE_FROM,
  PER_PHONES.DATE_TO,
  PER_PHONES.PHONE_TYPE,
  PER_PHONES.PHONE_NUMBER AS PHONE_MOBI
FROM
  PER_PHONES
  INNER JOIN X002_PEOPLE_CURR ON PER_PHONES.PARENT_ID = X002_PEOPLE_CURR.PERSON_ID AND PER_PHONES.DATE_FROM <=
    X002_PEOPLE_CURR.DATE_EMP_LOOKUP AND PER_PHONES.DATE_TO >= X002_PEOPLE_CURR.DATE_EMP_LOOKUP
WHERE
  PER_PHONES.PHONE_TYPE = 'M'
ORDER BY
  X002_PEOPLE_CURR.EMPLOYEE_NUMBER,
  PER_PHONES.DATE_FROM
