SELECT
  PER_PERIODS_OF_SERVICE.PERIOD_OF_SERVICE_ID,
  PER_PERIODS_OF_SERVICE.BUSINESS_GROUP_ID,
  PER_PERIODS_OF_SERVICE.PERSON_ID,
  PER_PERIODS_OF_SERVICE.DATE_START,
  PER_PERIODS_OF_SERVICE.ACCEPTED_TERMINATION_DATE,
  PER_PERIODS_OF_SERVICE.ACTUAL_TERMINATION_DATE,
  PER_PERIODS_OF_SERVICE.FINAL_PROCESS_DATE,
  PER_PERIODS_OF_SERVICE.LAST_STANDARD_PROCESS_DATE,
  PER_PERIODS_OF_SERVICE.LEAVING_REASON,
  HR_LOOKUPS.MEANING AS LEAVE_REASON_DESCRIP,
  PER_PERIODS_OF_SERVICE.LAST_UPDATE_DATE,
  PER_PERIODS_OF_SERVICE.LAST_UPDATED_BY,
  PER_PERIODS_OF_SERVICE.LAST_UPDATE_LOGIN,
  PER_PERIODS_OF_SERVICE.CREATED_BY,
  PER_PERIODS_OF_SERVICE.CREATION_DATE,
  PER_PERIODS_OF_SERVICE.COMMENTS,
  PER_ALL_PEOPLE_F.EMPLOYEE_NUMBER
FROM
  PER_PERIODS_OF_SERVICE
  LEFT JOIN HR_LOOKUPS ON HR_LOOKUPS.LOOKUP_CODE = PER_PERIODS_OF_SERVICE.LEAVING_REASON AND
   HR_LOOKUPS.LOOKUP_TYPE = "LEAV_REAS"  
  LEFT JOIN PER_ALL_PEOPLE_F ON PER_ALL_PEOPLE_F.PERSON_ID = PER_PERIODS_OF_SERVICE.PERSON_ID AND
   PER_PERIODS_OF_SERVICE.DATE_START >= PER_ALL_PEOPLE_F.EFFECTIVE_START_DATE AND
   PER_PERIODS_OF_SERVICE.DATE_START <= PER_ALL_PEOPLE_F.EFFECTIVE_END_DATE
