SELECT
  PER_PHONES.PARENT_ID,
  PER_PHONES.PHONE_ID,
  PER_PHONES.PHONE_TYPE,
  PER_PHONES.DATE_FROM,
  PER_PHONES.DATE_TO,
  PER_PHONES.PHONE_NUMBER
FROM
  PER_PHONES
WHERE
  PER_PHONES.PHONE_TYPE = 'W1'
ORDER BY
  PER_PHONES.PARENT_ID,
  PER_PHONES.DATE_FROM DESC
