SELECT
  PER_ADDRESSES.ADDRESS_ID,
  PER_ADDRESSES.PERSON_ID,
  PER_ADDRESSES.DATE_FROM,
  PER_ADDRESSES.DATE_TO,
  PER_ADDRESSES.STYLE,
  PER_ADDRESSES.ADDRESS_TYPE,
  PER_ADDRESSES.PRIMARY_FLAG,
  PER_ADDRESSES.ADDRESS_LINE1,
  PER_ADDRESSES.ADDRESS_LINE2,
  PER_ADDRESSES.ADDRESS_LINE3,
  PER_ADDRESSES.POSTAL_CODE,
  PER_ADDRESSES.TOWN_OR_CITY,
  PER_ADDRESSES.COUNTRY AS COUNTRY_CODE,
  HR_LOOKUPS.MEANING AS COUNTRY_LOOKUP,
  PER_ADDRESSES.REGION_1,
  PER_ADDRESSES.REGION_2,
  PER_ADDRESSES.REGION_3,
  PER_ADDRESSES.ADD_INFORMATION14,
  PER_ADDRESSES.ADD_INFORMATION15,
  PER_ADDRESSES.ADD_INFORMATION16,
  PER_ADDRESSES.ADD_INFORMATION17,
  PER_ADDRESSES.ADD_INFORMATION18,
  PER_ADDRESSES.CREATION_DATE,
  PER_ADDRESSES.CREATED_BY,
  PER_ADDRESSES.LAST_UPDATED_BY,
  PER_ADDRESSES.LAST_UPDATE_DATE,
  PER_ADDRESSES.PARTY_ID
FROM
  PER_ADDRESSES
  LEFT JOIN HR_LOOKUPS ON HR_LOOKUPS.LOOKUP_CODE = PER_ADDRESSES.COUNTRY AND HR_LOOKUPS.LOOKUP_TYPE =
    'GHR_US_POSTAL_COUNTRY_CODE'
