SELECT
  X000_COUNT_PEOPLE.PERSON_ID,
  X000_COUNT_PEOPLE.COUNT_PEO,
  X000_COUNT_PERIODOS.COUNT_POS,
  X000_COUNT_ASSIGNMENTS.COUNT_ASS
FROM
  X000_COUNT_PEOPLE
  LEFT JOIN X000_COUNT_ASSIGNMENTS ON X000_COUNT_PEOPLE.PERSON_ID = X000_COUNT_ASSIGNMENTS.PERSON_ID
  LEFT JOIN X000_COUNT_PERIODOS ON X000_COUNT_PERIODOS.PERSON_ID = X000_COUNT_PEOPLE.PERSON_ID
