SELECT
  X001_ASSIGNMENT_CURR.EMPLOYEE_NUMBER,
  X001_ASSIGNMENT_CURR.PERSON_ID,
  X000_PHONE_MOBI.PHONE_ID,
  X000_PHONE_MOBI.PHONE_TYPE,
  X000_PHONE_MOBI.DATE_FROM,
  X000_PHONE_MOBI.DATE_TO,
  X000_PHONE_MOBI.PHONE_NUMBER
FROM
  X000_PHONE_MOBI
  LEFT JOIN X001_ASSIGNMENT_CURR ON X000_PHONE_MOBI.PARENT_ID = X001_ASSIGNMENT_CURR.PERSON_ID AND
    X000_PHONE_MOBI.DATE_FROM <= X001_ASSIGNMENT_CURR.DATE_EMP_LOOKUP AND X000_PHONE_MOBI.DATE_TO >=
    X001_ASSIGNMENT_CURR.DATE_EMP_LOOKUP
WHERE
  X001_ASSIGNMENT_CURR.EMPLOYEE_NUMBER != ''
ORDER BY
  X001_ASSIGNMENT_CURR.EMPLOYEE_NUMBER,
  X000_PHONE_MOBI.DATE_FROM DESC
