SELECT
  PER_JOBS.JOB_ID,
  PER_JOBS.DATE_FROM,
  PER_JOBS.DATE_TO,
  PER_JOBS.JOB_DEFINITION_ID,
  PER_JOB_DEFINITIONS.SEGMENT1 AS JOB_NAME,
  PER_JOBS.NAME AS JOB_COMB,
  PER_JOB_DEFINITIONS.SEGMENT2 AS JOB_SEGMENT,
  PER_JOBS.ATTRIBUTE1,
  PER_JOBS.CREATION_DATE,
  PER_JOBS.CREATED_BY,
  PER_JOBS.LAST_UPDATE_DATE,
  PER_JOBS.LAST_UPDATED_BY,
  PER_JOBS.LAST_UPDATE_LOGIN,
  PER_JOBS.JOB_GROUP_ID,
  PER_JOB_DEFINITIONS.ID_FLEX_NUM
FROM
  PER_JOBS
  LEFT JOIN PER_JOB_DEFINITIONS ON PER_JOB_DEFINITIONS.JOB_DEFINITION_ID = PER_JOBS.JOB_DEFINITION_ID
ORDER BY
  PER_JOBS.JOB_ID
