SELECT
  X000_ORG_STRUCT_1.ORG_STRUCTURE_ELEMENT_ID,
  X000_ORG_STRUCT_1.BUSINESS_GROUP_ID,
  X000_ORG_STRUCT_1.ORG_STRUCTURE_VERSION_ID,
  X000_ORG_STRUCT_1.ORG1,
  X000_ORG_STRUCT_1.ORG2,
  PER_ORG_STRUCTURE_ELEMENTS.ORGANIZATION_ID_PARENT AS ORG3
FROM
  X000_ORG_STRUCT_1
  LEFT JOIN PER_ORG_STRUCTURE_ELEMENTS ON PER_ORG_STRUCTURE_ELEMENTS.ORGANIZATION_ID_CHILD = X000_ORG_STRUCT_1.ORG2
