SELECT
  PER_ALL_PEOPLE_F.PERSON_ID,
  PER_ALL_PEOPLE_F.PARTY_ID,
  PER_ALL_PEOPLE_F.EMPLOYEE_NUMBER,
  PER_ALL_PEOPLE_F.FULL_NAME,
  PER_ALL_PEOPLE_F.DATE_OF_BIRTH,
  PER_ALL_PEOPLE_F.SEX,
  PER_ALL_PEOPLE_F.NATIONAL_IDENTIFIER,
  PER_ALL_PEOPLE_F.EFFECTIVE_START_DATE,
  PER_ALL_PEOPLE_F.EFFECTIVE_END_DATE,
  PER_ALL_PEOPLE_F.EMAIL_ADDRESS,
  PER_ALL_PEOPLE_F.TITLE,
  HR_LOOKUPS_TITLE.MEANING AS TITLE_FULL,
  PER_ALL_PEOPLE_F.FIRST_NAME,
  PER_ALL_PEOPLE_F.MIDDLE_NAMES,
  PER_ALL_PEOPLE_F.LAST_NAME,
  PER_ALL_PEOPLE_F.PERSON_TYPE_ID,
  PER_PERSON_TYPES.USER_PERSON_TYPE,
  PER_ALL_PEOPLE_F.MARITAL_STATUS,
  PER_ALL_PEOPLE_F.NATIONALITY,
  HR_LOOKUPS_NATIONALITY.MEANING AS NATIONALITY_NAME,
  PER_ALL_PEOPLE_F.ATTRIBUTE1,
  PER_ALL_PEOPLE_F.ATTRIBUTE2 AS INT_MAIL,
  PER_ALL_PEOPLE_F.ATTRIBUTE3,
  PER_ALL_PEOPLE_F.ATTRIBUTE4 AS KNOWN_NAME,
  PER_ALL_PEOPLE_F.ATTRIBUTE5,
  PER_ALL_PEOPLE_F.ATTRIBUTE6,
  PER_ALL_PEOPLE_F.ATTRIBUTE7,
  PER_ALL_PEOPLE_F.PER_INFORMATION_CATEGORY,
  PER_ALL_PEOPLE_F.PER_INFORMATION1 AS TAX_NUMBER,
  PER_ALL_PEOPLE_F.PER_INFORMATION2,
  PER_ALL_PEOPLE_F.PER_INFORMATION3,
  PER_ALL_PEOPLE_F.PER_INFORMATION4 AS RACE_CODE,
  HR_LOOKUPS_RACE.MEANING AS RACE_DESC,  
  PER_ALL_PEOPLE_F.PER_INFORMATION5,
  PER_ALL_PEOPLE_F.PER_INFORMATION6 AS LANG_CODE,
  HR_LOOKUPS_LANG.MEANING AS LANG_DESC,  
  PER_ALL_PEOPLE_F.PER_INFORMATION7,
  PER_ALL_PEOPLE_F.PER_INFORMATION8,
  PER_ALL_PEOPLE_F.PER_INFORMATION9,
  PER_ALL_PEOPLE_F.PER_INFORMATION10,
  PER_ALL_PEOPLE_F.PER_INFORMATION11,
  PER_ALL_PEOPLE_F.PER_INFORMATION12,
  PER_ALL_PEOPLE_F.PER_INFORMATION13,
  PER_ALL_PEOPLE_F.PER_INFORMATION14,
  PER_ALL_PEOPLE_F.CREATED_BY,
  PER_ALL_PEOPLE_F.CREATION_DATE,
  PER_ALL_PEOPLE_F.LAST_UPDATE_DATE,
  PER_ALL_PEOPLE_F.LAST_UPDATED_BY,
  PER_ALL_PEOPLE_F.LAST_UPDATE_LOGIN,
  PER_ALL_PEOPLE_F.ORIGINAL_DATE_OF_HIRE,
  PER_ALL_PEOPLE_F.START_DATE,
  PER_ALL_PEOPLE_F.DATE_OF_DEATH,
  PER_ALL_PEOPLE_F.RECEIPT_OF_DEATH_CERT_DATE,
  PER_ALL_PEOPLE_F.OBJECT_VERSION_NUMBER,
  PER_ALL_PEOPLE_F.BUSINESS_GROUP_ID,
  PER_ALL_PEOPLE_F.CURRENT_EMP_OR_APL_FLAG,
  PER_ALL_PEOPLE_F.CURRENT_EMPLOYEE_FLAG,
  PER_ALL_PEOPLE_F.DATE_EMPLOYEE_DATA_VERIFIED,
  PER_ALL_PEOPLE_F.RESUME_EXISTS,
  PER_ALL_PEOPLE_F.RESUME_LAST_UPDATED,
  PER_ALL_PEOPLE_F.REGISTERED_DISABLED_FLAG,
  PER_ALL_PEOPLE_F.SECOND_PASSPORT_EXISTS,
  PER_ALL_PEOPLE_F.PREVIOUS_LAST_NAME
FROM
  PER_ALL_PEOPLE_F
  LEFT JOIN PER_PERSON_TYPES ON PER_PERSON_TYPES.PERSON_TYPE_ID = PER_ALL_PEOPLE_F.PERSON_TYPE_ID
  LEFT JOIN HR_LOOKUPS HR_LOOKUPS_NATIONALITY ON HR_LOOKUPS_NATIONALITY.LOOKUP_CODE = PER_ALL_PEOPLE_F.NATIONALITY AND
    HR_LOOKUPS_NATIONALITY.LOOKUP_TYPE = 'NATIONALITY'  
  LEFT JOIN HR_LOOKUPS HR_LOOKUPS_TITLE ON HR_LOOKUPS_TITLE.LOOKUP_CODE = PER_ALL_PEOPLE_F.TITLE AND
    HR_LOOKUPS_TITLE.LOOKUP_TYPE = 'TITLE'
  LEFT JOIN HR_LOOKUPS HR_LOOKUPS_RACE ON HR_LOOKUPS_RACE.LOOKUP_CODE = PER_ALL_PEOPLE_F.PER_INFORMATION4 AND
    HR_LOOKUPS_RACE.LOOKUP_TYPE = 'ZA_RACE'
  LEFT JOIN HR_LOOKUPS HR_LOOKUPS_LANG ON HR_LOOKUPS_LANG.LOOKUP_CODE = PER_ALL_PEOPLE_F.PER_INFORMATION6 AND
    HR_LOOKUPS_LANG.LOOKUP_TYPE = 'ZA_LANG_PREF'    
ORDER BY
  PER_ALL_PEOPLE_F.EMPLOYEE_NUMBER,
  PER_ALL_PEOPLE_F.EFFECTIVE_START_DATE
