SELECT
  X000_PER_ALL_ASSIGNMENTS.ASS_ID,
  X000_PER_ALL_ASSIGNMENTS.PERSON_ID,
  X000_PER_ALL_ASSIGNMENTS.ASSIGNMENT_NUMBER,
  X000_PER_ALL_ASSIGNMENTS.SERVICE_DATE_START,
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_START_DATE,
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_END_DATE,
  X000_PER_ALL_ASSIGNMENTS.SERVICE_DATE_ACTUAL_TERMINATION,
  X000_PER_ALL_ASSIGNMENTS.ORG_NAME,
  X000_PER_ALL_ASSIGNMENTS.ORGANIZATION_ID,
  X000_PER_ALL_ASSIGNMENTS.ORG_TYPE,
  X000_PER_ALL_ASSIGNMENTS.ORG_TYPE_DESC,
  X000_PER_ALL_ASSIGNMENTS.OE_CODE,
  X000_PER_ALL_ASSIGNMENTS.GRADE,
  X000_PER_ALL_ASSIGNMENTS.LEAVING_REASON,
  X000_PER_ALL_ASSIGNMENTS.LEAVE_REASON_DESCRIP,
  X000_PER_ALL_ASSIGNMENTS.GRADE_NAME,
  X000_PER_ALL_ASSIGNMENTS.POSITION,
  X000_PER_ALL_ASSIGNMENTS.POSITION_NAME,
  X000_PER_ALL_ASSIGNMENTS.ACAD_SUPP,
  X000_PER_ALL_ASSIGNMENTS.JOB_NAME,
  X000_PER_ALL_ASSIGNMENTS.JOB_SEGMENT_NAME,
  X000_PER_ALL_ASSIGNMENTS.LOCATION_CODE,
  X000_PER_ALL_ASSIGNMENTS.LOCATION_DESCRIPTION,
  X000_PER_ALL_ASSIGNMENTS.ASS_WEEK_LEN,
  X000_PER_ALL_ASSIGNMENTS.ASS_ATTRIBUTE2,
  X000_PER_ALL_ASSIGNMENTS.PEOPLE_GROUP_ID,
  X000_PER_ALL_ASSIGNMENTS.LEAVE_CODE,
  X000_PER_ALL_ASSIGNMENTS.SUPERVISOR_ID,
  X000_PER_ALL_ASSIGNMENTS.EMPLOYMENT_CATEGORY,
  X000_PER_ALL_ASSIGNMENTS.PRIMARY_FLAG
FROM
  X000_PER_ALL_ASSIGNMENTS
WHERE
  (X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_END_DATE >= Date('2018-01-01') AND
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_END_DATE <= Date('2018-12-31')) OR
  (X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_START_DATE >= Date('2018-01-01') AND
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_START_DATE <= Date('2018-12-31')) OR
  (X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_END_DATE >= Date('2018-12-31') AND
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_START_DATE <= Date('2018-01-01'))
ORDER BY
  X000_PER_ALL_ASSIGNMENTS.ASSIGNMENT_NUMBER,
  X000_PER_ALL_ASSIGNMENTS.EFFECTIVE_START_DATE DESC
