SELECT
  X002_PEOPLE_CURR.EMPLOYEE_NUMBER,
  X002_PEOPLE_CURR.DATE_OF_BIRTH,
  X002_PEOPLE_CURR.NAME_LIST,
  X002_PEOPLE_CURR.KNOWN_NAME,
  X002_PEOPLE_CURR.POSITION_FULL,
  X002_PEOPLE_CURR.OE_CODE
FROM
  X002_PEOPLE_CURR
WHERE
  StrfTime('%m-%d', X002_PEOPLE_CURR.DATE_OF_BIRTH) >= StrfTime('%m-%d', 'now') AND
  StrfTime('%m-%d', X002_PEOPLE_CURR.DATE_OF_BIRTH) <= StrfTime('%m-%d', 'now', '+7 day')
ORDER BY
  X002_PEOPLE_CURR.POSITION_FULL,
  StrfTime('%m-%d', X002_PEOPLE_CURR.DATE_OF_BIRTH)
