SELECT
  ACCDEFERMENT.KACCDEFERMENTID,
  ACCDEFERMENT.FACCID,
  STUDACC.FBUSENTID,
  ACCDEFERMENT.DATEARRANGED,
  SYSTEMUSER.FUSERBUSINESSENTITYID,
  ACCDEFERMENT.STARTDATE,
  ACCDEFERMENT.ENDDATE,
  ACCDEFERMENT.TOTALAMOUNT,
  CODEDESCRIPTION.CODESHORTDESCRIPTION AS SUBACCOUNTTYPE,
  CODEDESCRIPTION1.CODESHORTDESCRIPTION AS DEFERMENTTYPE,
  CODEDESCRIPTION2.CODESHORTDESCRIPTION AS DEFERMENTREASON,
  ACCDEFERMENT.NOTE,
  ACCDEFERMENT.FAUDITUSERCODE,
  ACCDEFERMENT.AUDITDATETIME,
  ACCDEFERMENT.FAUDITSYSTEMFUNCTIONID
FROM
  ACCDEFERMENT
  LEFT JOIN CODEDESCRIPTION ON CODEDESCRIPTION.KCODEDESCID = ACCDEFERMENT.FSUBACCTYPECODEID
  LEFT JOIN CODEDESCRIPTION CODEDESCRIPTION1 ON CODEDESCRIPTION1.KCODEDESCID = ACCDEFERMENT.FDEFERMENTTYPECODEID
  LEFT JOIN CODEDESCRIPTION CODEDESCRIPTION2 ON CODEDESCRIPTION2.KCODEDESCID = ACCDEFERMENT.FDEFERMENTREASONCODEID
  LEFT JOIN STUDACC ON STUDACC.KACCID = ACCDEFERMENT.FACCID
  LEFT JOIN SYSTEMUSER ON SYSTEMUSER.KUSERCODE = ACCDEFERMENT.FAUDITUSERCODE
WHERE
  CODEDESCRIPTION.KSYSTEMLANGUAGECODEID = 3 AND
  CODEDESCRIPTION1.KSYSTEMLANGUAGECODEID = 3 AND
  CODEDESCRIPTION2.KSYSTEMLANGUAGECODEID = 3
ORDER BY
  STUDACC.FBUSENTID,
  ACCDEFERMENT.AUDITDATETIME
