SELECT
  X000_deferments.KACCDEFERMENTID,
  X000_deferments.FBUSENTID AS 'STUDENT',
  STUDENTSITE.FDEBTCOLLECTIONSITE AS 'CAMPUS',
  X000_deferments.DATEARRANGED,
  X000_deferments.FUSERBUSINESSENTITYID AS 'EMPLOYEE',
  X000_deferments.STARTDATE AS 'DATESTART',
  X000_deferments.ENDDATE AS 'DATEEND',
  X000_deferments.TOTALAMOUNT,
  X000_deferments.SUBACCOUNTTYPE,
  X000_deferments.DEFERMENTTYPE,
  X000_deferments.DEFERMENTREASON,
  X000_deferments.NOTE,
  X000_deferments.FAUDITUSERCODE,
  X000_deferments.AUDITDATETIME,
  X000_deferments.FAUDITSYSTEMFUNCTIONID,
  STUDENTSITE.FADMISSIONSITE,
  STUDENTSITE.FMAINQUALSITE
FROM
  X000_deferments
  LEFT JOIN STUDENTSITE ON STUDENTSITE.KSTUDENTBUSENTID = X000_deferments.FBUSENTID
WHERE
  STUDENTSITE.KSTARTDATETIME <= X000_deferments.DATEARRANGED AND
  STUDENTSITE.ENDDATETIME > X000_deferments.DATEARRANGED AND
  X000_deferments.STARTDATE >= Date('2018-01-01') AND
  X000_deferments.ENDDATE <= Date('2018-12-31')
