Select
    X103_PER_ABSENCE_ATTENDANCES_PREV.LEAVE_TYPE,
    Count(X103_PER_ABSENCE_ATTENDANCES_PREV.AUTHORISING_PERSON_ID) As Count_AUTHORISING_PERSON_ID
From
    X103_PER_ABSENCE_ATTENDANCES_PREV
Group By
    X103_PER_ABSENCE_ATTENDANCES_PREV.LEAVE_TYPE