Select
    MASTER.ORG,
    MASTER.LOC,
    MASTER.EMPLOYEE_NUMBER,
    MASTER.GRADE,
    BENCH.GRADE As GRADE_BENCH,
    MASTER.EMPLOYMENT_CATEGORY,
    MASTER.ACAD_SUPP,
    MASTER.PERSON_TYPE
From
    X007_grade_leave_master MASTER Left Join
    X007_grade_master BENCH On BENCH.CATEGORY = MASTER.EMPLOYMENT_CATEGORY
            And BENCH.TYPE = MASTER.PERSON_TYPE
            And BENCH.ACADSUPP = MASTER.ACAD_SUPP