SELECT
  main.ORGUNIT.KORGUNITNUMBER,
  main.ORGUNIT.STARTDATE,
  main.ORGUNIT.ENDDATE,
  main.ORGUNIT.FORGUNITTYPECODEID,
  main.ORGUNIT.FORGUNITTYPECODE,
  main.ORGUNIT.ISSITE,
  main.ORGUNIT.LOCKSTAMP,
  main.ORGUNIT.AUDITDATETIME,
  main.ORGUNIT.FAUDITSYSTEMFUNCTIONID,
  main.ORGUNIT.FAUDITUSERCODE,
  main.X000_Orgunitname.KSTARTDATE,
  main.X000_Orgunitname.ENDDATE AS ENDDATE1,
  main.X000_Orgunitname.KORT,
  main.X000_Orgunitname.LANK,
  main.X000_Orgunitname.SHORT,
  main.X000_Orgunitname.LONG,
  main.X000_Codedescription.LONG AS UNIT_TYPE
FROM
  main.ORGUNIT
  LEFT JOIN main.X000_Orgunitname ON main.X000_Orgunitname.KORGUNITNUMBER = main.ORGUNIT.KORGUNITNUMBER
  LEFT JOIN main.X000_Codedescription ON main.X000_Codedescription.KCODEDESCID = main.ORGUNIT.FORGUNITTYPECODEID
WHERE
  main.X000_Orgunitname.KSTARTDATE <= main.ORGUNIT.STARTDATE AND
  main.X000_Orgunitname.ENDDATE >= main.ORGUNIT.STARTDATE
ORDER BY
  main.ORGUNIT.KORGUNITNUMBER
