SELECT
  main.ORGUNITNAME.KORGUNITNUMBER,
  main.ORGUNITNAME.KSTARTDATE,
  main.ORGUNITNAME.ENDDATE,
  main.ORGUNITNAME.SHORTNAME AS KORT,
  main.ORGUNITNAME.LONGNAME AS LANK,
  ORGUNITNAME1.SHORTNAME AS SHORT,
  ORGUNITNAME1.LONGNAME AS LONG
FROM
  main.ORGUNITNAME
  LEFT JOIN main.ORGUNITNAME ORGUNITNAME1 ON ORGUNITNAME1.KORGUNITNUMBER = main.ORGUNITNAME.KORGUNITNUMBER AND
    ORGUNITNAME1.KSTARTDATE = main.ORGUNITNAME.KSTARTDATE
WHERE
  main.ORGUNITNAME.KSYSTEMLANGUAGECODEID = 2 AND
  ORGUNITNAME1.KSYSTEMLANGUAGECODEID = 3
