Select
    PARTYEXTERNALREFERENCE.KEXTERNALREFERENCECODEID,
    CODEDESCRIPTION.CODELONGDESCRIPTION,
    Count(CODEDESCRIPTION.KCODEDESCID) As Total_KCODEDESCID
From
    PARTYEXTERNALREFERENCE Inner Join
    CODEDESCRIPTION On CODEDESCRIPTION.KCODEDESCID = PARTYEXTERNALREFERENCE.KEXTERNALREFERENCECODEID
Group By
    PARTYEXTERNALREFERENCE.KEXTERNALREFERENCECODEID