Select
    X000_Party.FTITLECODEID,
    X000_Party.TITLE,
    Count(X000_Party.KBUSINESSENTITYID) As Count_KBUSINESSENTITYID
From
    X000_Party
Group By
    X000_Party.FTITLECODEID,
    X000_Party.TITLE