SELECT
  PRESENTOUENROLPRESENTCAT.KENROLMENTPRESENTATIONID,
  PRESENTOUENROLPRESENTCAT.FENROLMENTCATEGORYCODEID,
  X000_CODEDESC_ENROLCAT.LONG AS ENROL_CAT_E,
  PRESENTOUENROLPRESENTCAT.FPRESENTATIONCATEGORYCODEID,
  X000_CODEDESC_PRESENTCAT.LONG AS PRESENT_CAT_E,
  PRESENTOUENROLPRESENTCAT.STARTDATE,
  PRESENTOUENROLPRESENTCAT.ENDDATE,
  PRESENTOUENROLPRESENTCAT.FQUALPRESENTINGOUID,
  PRESENTOUENROLPRESENTCAT.FMODULEPRESENTINGOUID,
  PRESENTOUENROLPRESENTCAT.FPROGRAMPRESENTINGOUID,
  PRESENTOUENROLPRESENTCAT.EXAMSUBMINIMUM,
  PRESENTOUENROLPRESENTCAT.FAUDITSYSTEMFUNCTIONID,
  PRESENTOUENROLPRESENTCAT.AUDITDATETIME,
  PRESENTOUENROLPRESENTCAT.FAUDITUSERCODE,
  X000_CODEDESC_ENROLCAT.LANK AS ENROL_CAT_A,
  X000_CODEDESC_PRESENTCAT.LANK AS PRESENT_CAT_A
FROM
  PRESENTOUENROLPRESENTCAT
  LEFT JOIN X000_Codedescription X000_CODEDESC_ENROLCAT ON X000_CODEDESC_ENROLCAT.KCODEDESCID =
    PRESENTOUENROLPRESENTCAT.FENROLMENTCATEGORYCODEID
  LEFT JOIN X000_Codedescription X000_CODEDESC_PRESENTCAT ON X000_CODEDESC_PRESENTCAT.KCODEDESCID =
    PRESENTOUENROLPRESENTCAT.FPRESENTATIONCATEGORYCODEID
