SELECT
  main.QUALIFICATION.KACADEMICPROGRAMID,
  main.QUALIFICATION.STARTDATE,
  main.QUALIFICATION.ENDDATE,
  main.QUALIFICATION.QUALIFICATIONCODE,
  X000_Codedescription4.LONG AS QUAL_TYPE,
  main.X000_Codedescription.LANK AS MIN,
  X000_Codedescription1.LONG AS MIN_UNIT,
  X000_Codedescription2.LONG AS MAX,
  X000_Codedescription3.LONG AS MAX_UNIT,
  main.QUALIFICATION.AUDITDATETIME,
  main.QUALIFICATION.FAUDITSYSTEMFUNCTIONID,
  main.QUALIFICATION.FAUDITUSERCODE,
  X000_Codedescription5.LONG AS CERT_TYPE,
  X000_Codedescription6.LONG AS LEVY_TYPE,
  main.QUALIFICATION.ISVATAPPLICABLE,
  main.QUALIFICATION.ISPRESENTEDBEFOREAPPROVAL,
  main.QUALIFICATION.ISDIRECTED
FROM
  main.QUALIFICATION
  LEFT JOIN main.X000_Codedescription ON main.X000_Codedescription.KCODEDESCID = main.QUALIFICATION.FMINDURATIONCODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription1 ON X000_Codedescription1.KCODEDESCID =
    main.QUALIFICATION.FMINDURPERIODUNITCODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription2 ON X000_Codedescription2.KCODEDESCID =
    main.QUALIFICATION.FMAXDURATIONCODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription3 ON X000_Codedescription3.KCODEDESCID =
    main.QUALIFICATION.FMAXDURPERIODUNITCODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription4 ON X000_Codedescription4.KCODEDESCID =
    main.QUALIFICATION.FQUALIFICATIONTYPECODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription5 ON X000_Codedescription5.KCODEDESCID =
    main.QUALIFICATION.FCERTIFICATETYPECODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription6 ON X000_Codedescription6.KCODEDESCID =
    main.QUALIFICATION.FLEVYLEVELCODEID
