SELECT
  main.X101_Stud_curr_qual1.KSTUDBUSENTID,
  main.X101_Stud_curr_qual1.KENROLSTUDID,
  main.X101_Stud_curr_qual1.DATEQUALLEVELSTARTED,
  main.X101_Stud_curr_qual1.DATEENROL,
  main.X101_Stud_curr_qual1.STARTDATE,
  main.X101_Stud_curr_qual1.ENDDATE,
  main.X101_Stud_curr_qual1.ISHEMISSUBSIDY,
  main.X101_Stud_curr_qual1.ISMAINQUALLEVEL,
  main.X101_Stud_curr_qual1.ENROLACADEMICYEAR,
  main.X101_Stud_curr_qual1.ENROLHISTORYYEAR,
  main.X101_Stud_curr_qual1.FSTUDACTIVECODEID,
  main.X101_Stud_curr_qual1.ACTIVE_IND,
  main.X101_Stud_curr_qual1.FENTRYLEVELCODEID,
  main.X101_Stud_curr_qual1.ENTRY_LEVEL,
  main.X101_Stud_curr_qual1.FENROLMENTCATEGORYCODEID,
  main.X101_Stud_curr_qual1.ENROL_CAT,
  main.X101_Stud_curr_qual1.FPRESENTATIONCATEGORYCODEID,
  main.X101_Stud_curr_qual1.PRESENT_CAT,
  main.X101_Stud_curr_qual1.FBLACKLISTCODEID,
  main.X101_Stud_curr_qual1.BLACKLIST,
  main.X101_Stud_curr_qual1.ISCONDITIONALREG,
  main.X101_Stud_curr_qual1.MARKSFINALISEDDATE,
  main.X101_Stud_curr_qual1.EXAMSUBMINIMUM,
  main.X101_Stud_curr_qual1.ISCUMLAUDE,
  main.X101_Stud_curr_qual1.FGRADCERTLANGUAGECODEID,
  main.X101_Stud_curr_qual1.ISPOSSIBLEGRADUATE,
  main.X101_Stud_curr_qual1.FGRADUATIONCEREMONYID,
  main.X101_Stud_curr_qual1.FACCEPTANCETESTCODEID,
  main.X101_Stud_curr_qual1.FENROLMENTPRESENTATIONID,
  main.X101_Stud_curr_qual1.FQUALPRESENTINGOUID,
  main.QUALLEVELPRESENTINGOU.FBUSINESSENTITYID,
  main.QUALLEVELPRESENTINGOU.FQUALLEVELAPID,
  main.QUALIFICATIONLEVEL.FFIELDOFSTUDYAPID,
  main.QUALIFICATIONLEVEL.STARTDATE AS QUAL_LEVEL_STARTDATE,
  main.QUALIFICATIONLEVEL.ENDDATE AS QUAL_LEVEL_ENDDATE,
  main.QUALIFICATIONLEVEL.FFINALSTATUSCODEID,
  main.QUALIFICATIONLEVEL.FLEVYCATEGORYCODEID,
  main.QUALIFICATIONLEVEL.QUALIFICATIONLEVEL,
  main.X000_Orgunitinstance.FORGUNITNUMBER,
  main.X000_Orgunitinstance.ORGUNIT_TYPE,
  main.X000_Orgunitinstance.ORGUNIT_NAME,
  main.X000_Orgunitinstance.FSITEORGUNITNUMBER,
  main.X000_Codedescription.LONG AS QUAL_LEVEL_STATUS_FINAL,
  X000_Codedescription1.LONG AS QUAL_LEVEL_LEVY_CAT
FROM
  main.X101_Stud_curr_qual1
  LEFT JOIN main.QUALLEVELPRESENTINGOU ON main.QUALLEVELPRESENTINGOU.KPRESENTINGOUID =
    main.X101_Stud_curr_qual1.FQUALPRESENTINGOUID
  LEFT JOIN main.QUALIFICATIONLEVEL ON main.QUALIFICATIONLEVEL.KACADEMICPROGRAMID =
    main.QUALLEVELPRESENTINGOU.FQUALLEVELAPID
  LEFT JOIN main.X000_Orgunitinstance ON main.X000_Orgunitinstance.KBUSINESSENTITYID =
    main.QUALLEVELPRESENTINGOU.FBUSINESSENTITYID
  LEFT JOIN main.X000_Codedescription ON main.X000_Codedescription.KCODEDESCID =
    main.QUALIFICATIONLEVEL.FFINALSTATUSCODEID
  LEFT JOIN main.X000_Codedescription X000_Codedescription1 ON X000_Codedescription1.KCODEDESCID =
    main.QUALIFICATIONLEVEL.FLEVYCATEGORYCODEID
