SELECT
  MODULEENROLSTUD_CURR.KSTUDBUSENTID,
  MODULEENROLSTUD_CURR.KENROLSTUDID,
  MODULEENROLSTUD_CURR.FQUALLEVELSTUDBUSENTID,
  MODULEENROLSTUD_CURR.FQUALLEVELENROLSTUDID,
  MODULEENROLSTUD_CURR.DATEENROL,
  MODULEENROLSTUD_CURR.STARTDATE,
  MODULEENROLSTUD_CURR.ENDDATE,
  MODULEENROLSTUD_CURR.FENROLMENTPRESENTATIONID,
  X002bb_Module_present_enrol.ENROL_CAT_E,
  X002bb_Module_present_enrol.ENROL_CAT_A,
  X002bb_Module_present_enrol.PRESENT_CAT_E,
  X002bb_Module_present_enrol.PRESENT_CAT_A,
  X002bb_Module_present_enrol.FSITEORGUNITNUMBER,
  X002bb_Module_present_enrol.ORGUNIT_TYPE,
  X002bb_Module_present_enrol.ORGUNIT_NAME,
  X002bb_Module_present_enrol.FMODULEAPID,
  X002bb_Module_present_enrol.COURSECODE,
  X002bb_Module_present_enrol.COURSELEVEL,
  X002bb_Module_present_enrol.COURSEMODULE,
  X002bb_Module_present_enrol.FCOURSEGROUPCODEID,
  X002bb_Module_present_enrol.NAME_GROUP,
  X002bb_Module_present_enrol.NAAM_GROEP,
  X002bb_Module_present_enrol.ISEXAMMODULE,
  X002bb_Module_present_enrol.EXAMSUBMINIMUM,
  MODULEENROLSTUD_CURR.FEXAMCENTREMODAPID,
  MODULEENROLSTUD_CURR.FCOMPLETEREASONCODEID,
  X000_CODEDESC_COMPLETEREASON.LONG AS COMPLETE_REASON_E,
  X000_CODEDESC_COMPLETEREASON.LANK AS COMPLETE_REASON_A,
  MODULEENROLSTUD_CURR.FPRESENTATIONLANGUAGEID,
  MODULEENROLSTUD_CURR.FMODULETYPECODEID,
  X000_CODEDESC_MODULETYPE.LONG AS MODULE_TYPE_E,
  X000_CODEDESC_MODULETYPE.LANK AS MODULE_TYPE_A
FROM
  MODULEENROLSTUD_CURR
  LEFT JOIN X002bb_Module_present_enrol ON X002bb_Module_present_enrol.KENROLMENTPRESENTATIONID =
    MODULEENROLSTUD_CURR.FENROLMENTPRESENTATIONID
  LEFT JOIN X000_Codedescription X000_CODEDESC_COMPLETEREASON ON X000_CODEDESC_COMPLETEREASON.KCODEDESCID =
    MODULEENROLSTUD_CURR.FCOMPLETEREASONCODEID
  LEFT JOIN X000_Codedescription X000_CODEDESC_MODULETYPE ON X000_CODEDESC_MODULETYPE.KCODEDESCID =
    MODULEENROLSTUD_CURR.FMODULETYPECODEID
