SELECT
  MODULE.KACADEMICPROGRAMID AS MODULE_ID,
  MODULE.STARTDATE,
  MODULE.ENDDATE,
  MODULE.ISRESEARCHMODULE,
  COURSE.COURSECODE,
  COURSELEVEL.COURSELEVEL,
  MODULE.COURSEMODULE
FROM
  MODULE
  LEFT JOIN COURSELEVEL ON COURSELEVEL.KACADEMICPROGRAMID = MODULE.FCOURSELEVELAPID
  LEFT JOIN COURSE ON COURSE.KACADEMICPROGRAMID = COURSELEVEL.FCOURSEAPID
