SELECT
  FINAID.KFINAIDID,
  FINAID.FFINAIDINSTBUSENTID,
  FINAID.FINAIDCODE,
  FINAIDNAME.FINAIDNAME,
  FINAIDNAAM.FINAIDNAME AS FINAIDNAAM,
  FINAID.FTYPECODEID,
  X000_Codedescription.LONG AS TYPE_E,
  X000_Codedescription.LANK AS TYPE_A,
  FINAID.FFINAIDCATCODEID,
  X000_CODEDESC_FINAIDCATE.LONG AS BURS_CATE_E,
  X000_CODEDESC_FINAIDCATE.LANK AS BURS_CATE_A,
  FINAID.ISAUTOAPPL,
  FINAID.ISWWWAPPLALLOWED,
  FINAID.FINAIDYEARS,
  FINAID.STARTDATE,
  FINAID.ENDDATE,
  FINAID.FFUNDTYPECODEID,
  X000_Codedesc_fundtype.LONG AS FUND_TYPE_E,
  X000_Codedesc_fundtype.LANK AS FUND_TYPE_A,
  FINAID.FSTUDYTYPECODEID,
  X000_Codedesc_studytype.LONG AS STUDY_TYPE_E,
  X000_Codedesc_studytype.LANK AS STUDY_TYPE_A,
  FINAID.FPROCESSID,
  FINAID.AUDITDATETIME,
  FINAID.FAUDITUSERCODE,
  FINAID.FAUDITSYSTEMFUNCTIONID
FROM
  FINAID
  LEFT JOIN X000_Codedescription X000_CODEDESC_FINAIDCATE ON X000_CODEDESC_FINAIDCATE.KCODEDESCID =
    FINAID.FFINAIDCATCODEID
  LEFT JOIN FINAIDNAME ON FINAIDNAME.FFINAIDID = FINAID.KFINAIDID AND FINAIDNAME.KSYSTEMLANGUAGECODEID = '3'
  LEFT JOIN FINAIDNAME FINAIDNAAM ON FINAIDNAAM.FFINAIDID = FINAID.KFINAIDID AND FINAIDNAAM.KSYSTEMLANGUAGECODEID = '2'
  LEFT JOIN X000_Codedescription ON X000_Codedescription.KCODEDESCID = FINAID.FTYPECODEID
  LEFT JOIN X000_Codedescription X000_Codedesc_fundtype ON X000_Codedesc_fundtype.KCODEDESCID = FINAID.FFUNDTYPECODEID
  LEFT JOIN X000_Codedescription X000_Codedesc_studytype ON X000_Codedesc_studytype.KCODEDESCID =
    FINAID.FSTUDYTYPECODEID
