SELECT
  PARTYEXTERNALREFERENCE.KBUSINESSENTITYID,
  PARTYEXTERNALREFERENCE.KEXTERNALREFERENCECODEID,
  X000_Codedesc_partyextref.LONG,
  X000_Codedesc_partyextref.LANK,
  PARTYEXTERNALREFERENCE.EXTERNALREFERENCENUMBER,
  PARTYEXTERNALREFERENCE.STARTDATE,
  PARTYEXTERNALREFERENCE.ENDDATE,
  PARTYEXTERNALREFERENCE.REFERENCECODE,
  PARTYEXTERNALREFERENCE.OTHERDESCRIPTION,
  PARTYEXTERNALREFERENCE.LOCKSTAMP,
  PARTYEXTERNALREFERENCE.AUDITDATETIME,
  PARTYEXTERNALREFERENCE.FAUDITSYSTEMFUNCTIONID,
  PARTYEXTERNALREFERENCE.FAUDITUSERCODE
FROM
  PARTYEXTERNALREFERENCE
  LEFT JOIN X000_Codedescription X000_Codedesc_partyextref ON X000_Codedesc_partyextref.KCODEDESCID =
    PARTYEXTERNALREFERENCE.KEXTERNALREFERENCECODEID
