Select
    ia_assignment.ia_assi_auto,
    ia_assignment.ia_user_sysid,
    ia_assignment.ia_assi_year,
    ia_assignment.ia_assi_period,
    ia_assignment.ia_assi_file,
    ia_assignment.ia_assi_startdate,
    ia_assignment.ia_assi_completedate,
    ia_assignment.ia_assi_findingdate,
    ia_assignment.ia_assi_proofdate,
    ia_assignment.ia_assi_si_caseyear,
    ia_assignment.ia_assi_si_casenumber,
    ia_assignment.ia_assi_si_reportdate,
    ia_assignment.ia_assi_name
From
    ia_assignment