SELECT
  PAY_ELEMENT_ENTRIES_F_CURR.ASSIGNMENT_ID,
  PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_ENTRY_ID,
  PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE,
  PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_END_DATE,
  PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_LINK_ID,
  PAY_ELEMENT_ENTRIES_F_CURR.CREATOR_TYPE,
  PAY_ELEMENT_ENTRIES_F_CURR.ENTRY_TYPE,
  PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_TYPE_ID,
  PAY_ELEMENT_ENTRY_VALUES_F_CURR.ELEMENT_ENTRY_VALUE_ID,
  PAY_ELEMENT_ENTRY_VALUES_F_CURR.INPUT_VALUE_ID,
  PAY_ELEMENT_ENTRY_VALUES_F_CURR.SCREEN_ENTRY_VALUE,
  PAY_ELEMENT_TYPES_F.ELEMENT_NAME,
  PAY_ELEMENT_TYPES_F.REPORTING_NAME,
  PAY_ELEMENT_TYPES_F.DESCRIPTION
FROM
  PAY_ELEMENT_ENTRIES_F_CURR
  LEFT JOIN PAY_ELEMENT_ENTRY_VALUES_F_CURR ON PAY_ELEMENT_ENTRY_VALUES_F_CURR.ELEMENT_ENTRY_ID =
    PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_ENTRY_ID AND PAY_ELEMENT_ENTRY_VALUES_F_CURR.EFFECTIVE_START_DATE <=
    PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE AND PAY_ELEMENT_ENTRY_VALUES_F_CURR.EFFECTIVE_END_DATE >= PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE
  LEFT JOIN PAY_ELEMENT_TYPES_F ON PAY_ELEMENT_TYPES_F.ELEMENT_TYPE_ID = PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_TYPE_ID AND
    PAY_ELEMENT_TYPES_F.EFFECTIVE_START_DATE <= PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE AND PAY_ELEMENT_TYPES_F.EFFECTIVE_END_DATE >=
    PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE
WHERE
  PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_START_DATE <= Date('2019-01-31') AND
  PAY_ELEMENT_ENTRIES_F_CURR.EFFECTIVE_END_DATE >= Date('2019-01-31') AND
  PAY_ELEMENT_ENTRY_VALUES_F_CURR.INPUT_VALUE_ID = 691
