SELECT
  PAY_RUN_BALANCES_CURR.ASSIGNMENT_ID,
  PAY_RUN_BALANCES_CURR.EFFECTIVE_DATE,
  PAY_RUN_BALANCES_CURR.BALANCE_VALUE,
  PAY_RUN_BALANCES_CURR.RUN_BALANCE_ID,
  PAY_RUN_BALANCES_CURR.DEFINED_BALANCE_ID,
  PAY_DEFINED_BALANCES.BALANCE_TYPE_ID,
  PAY_BALANCE_TYPES.BALANCE_NAME,
  PAY_BALANCE_TYPES.REPORTING_NAME,
  PAY_BALANCE_TYPES.BALANCE_UOM,
  PAY_BALANCE_TYPES.BALANCE_CATEGORY_ID
FROM
  PAY_RUN_BALANCES_CURR
  LEFT JOIN PAY_DEFINED_BALANCES ON PAY_DEFINED_BALANCES.DEFINED_BALANCE_ID = PAY_RUN_BALANCES_CURR.DEFINED_BALANCE_ID
  LEFT JOIN PAY_BALANCE_TYPES ON PAY_BALANCE_TYPES.BALANCE_TYPE_ID = PAY_DEFINED_BALANCES.BALANCE_TYPE_ID
