SELECT
  PAY_ELEMENT_ENTRIES_F_CURR.*,
  PAY_ELEMENT_ENTRY_VALUES_F_CURR.*
FROM
  PAY_ELEMENT_ENTRIES_F_CURR
  LEFT JOIN PAY_ELEMENT_ENTRY_VALUES_F_CURR ON PAY_ELEMENT_ENTRY_VALUES_F_CURR.ELEMENT_ENTRY_ID =
    PAY_ELEMENT_ENTRIES_F_CURR.ELEMENT_ENTRY_ID
