SELECT
  PAY_ASSIGNMENT_ACTIONS.ASSIGNMENT_ACTION_ID,
  Count(PAY_ASSIGNMENT_ACTIONS.ASSIGNMENT_ID) AS Count_ASSIGNMENT_ID
FROM
  PAY_ASSIGNMENT_ACTIONS
GROUP BY
  PAY_ASSIGNMENT_ACTIONS.ASSIGNMENT_ACTION_ID
