SELECT
  PAY_PAYROLL_ACTIONS.PAYROLL_ACTION_ID,
  PAY_PAYROLL_ACTIONS.ACTION_TYPE,
  HR_LOOKUPS.MEANING AS ACTION_DESCRIP,
  PAY_PAYROLL_ACTIONS.EFFECTIVE_DATE,
  PAY_PAYROLL_ACTIONS.DATE_EARNED,
  PAY_PAYROLL_ACTIONS.ACTION_SEQUENCE,
  PAY_PAYROLL_ACTIONS.TIME_PERIOD_ID,
  PAY_PAYROLL_ACTIONS.LAST_UPDATE_DATE,
  PAY_PAYROLL_ACTIONS.LAST_UPDATED_BY,
  PAY_PAYROLL_ACTIONS.LAST_UPDATE_LOGIN,
  PAY_PAYROLL_ACTIONS.CREATED_BY,
  PAY_PAYROLL_ACTIONS.CREATION_DATE,
  PAY_PAYROLL_ACTIONS.BUSINESS_GROUP_ID,
  PAY_PAYROLL_ACTIONS.PAYROLL_ID,
  PAY_PAYROLL_ACTIONS.CONSOLIDATION_SET_ID,
  PAY_PAYROLL_ACTIONS.BATCH_ID,
  PAY_PAYROLL_ACTIONS.BATCH_PROCESS_MODE,
  PAY_PAYROLL_ACTIONS.START_DATE,
  PAY_PAYROLL_ACTIONS.END_DATE
FROM
  PAY_PAYROLL_ACTIONS
  LEFT JOIN HR_LOOKUPS ON HR_LOOKUPS.LOOKUP_CODE = PAY_PAYROLL_ACTIONS.ACTION_TYPE AND HR_LOOKUPS.LOOKUP_TYPE =
    "ACTION_TYPE"
