Select
    ppa.DATE_EARNED,
    ppa.PAYROLL_ACTION_ID,
    pac.ASSIGNMENT_ACTION_ID,
    prr.ELEMENT_TYPE_ID,
    pet.ELEMENT_NAME,
    pet.REPORTING_NAME,
    prr.RUN_RESULT_ID,
    prrv.RESULT_VALUE,
    pac.ASSIGNMENT_ID,
    ass.EFFECTIVE_END_DATE As EFFECTIVE_END_DATE_ASS,
    per.PERSON_ID,
    per.EFFECTIVE_END_DATE As EFFECTIVE_END_DATE_PER,
    per.EMPLOYEE_NUMBER,
    per.FULL_NAME
From
    HR.PAY_ASSIGNMENT_ACTIONS pac Inner Join
    HR.PAY_PAYROLL_ACTIONS ppa On ppa.PAYROLL_ACTION_ID = pac.PAYROLL_ACTION_ID Inner Join
    HR.PAY_RUN_RESULTS prr On prr.ASSIGNMENT_ACTION_ID = pac.ASSIGNMENT_ACTION_ID Inner Join
    HR.PAY_ELEMENT_TYPES_F pet On pet.ELEMENT_TYPE_ID = prr.ELEMENT_TYPE_ID Inner Join
    HR.PAY_INPUT_VALUES_F piv On piv.ELEMENT_TYPE_ID = pet.ELEMENT_TYPE_ID Inner Join
    HR.PAY_RUN_RESULT_VALUES prrv On prrv.INPUT_VALUE_ID = piv.INPUT_VALUE_ID
            And prrv.RUN_RESULT_ID = prr.RUN_RESULT_ID Inner Join
    HR.PER_ALL_ASSIGNMENTS_F ass On ass.ASSIGNMENT_ID = pac.ASSIGNMENT_ID Inner Join
    HR.PER_ALL_PEOPLE_F per On per.PERSON_ID = ass.PERSON_ID
Where
    ass.EFFECTIVE_END_DATE = To_Date('4712-12-31', 'RRRR-MM-DD') And
    per.EFFECTIVE_END_DATE = To_Date('4712-12-31', 'RRRR-MM-DD') And
    per.EMPLOYEE_NUMBER = '21162395'