Select
    paa.ASSIGNMENT_ACTION_ID,
    paa.ASSIGNMENT_ID,
    paa.PAYROLL_ACTION_ID,
    paa.PAYROLL_ACTION_ID#1,
    paa.ACTION_STATUS,
    ppa.PAYROLL_ACTION_ID As PAYROLL_ACTION_PPA,
    ppa.ACTION_TYPE,
    ppa.EFFECTIVE_DATE,
    ppa.ACTION_SEQUENCE,
    paaf.ASSIGNMENT_ID As ASSIGNMENT_PAAF,
    paaf.EFFECTIVE_START_DATE As EFFECTIVE_START_PAAF,
    paaf.EFFECTIVE_END_DATE As EFFECTIVE_END_PAAF,
    paaf.ORGANIZATION_ID,
    papf.PERSON_ID,
    papf.EFFECTIVE_START_DATE As EFFECTIVE_START_PAPF,
    papf.EFFECTIVE_END_DATE As EFFECTIVE_END_PAPF,
    papf.EMPLOYEE_NUMBER,
    papf.FULL_NAME
From
    HR.PAY_ASSIGNMENT_ACTIONS paa,
    APPS.PAY_PAYROLL_ACTIONS ppa,
    APPS.PER_ALL_ASSIGNMENTS_F paaf,
    HR.PER_ALL_PEOPLE_F papf
Where
    paa.ASSIGNMENT_ID = paaf.ASSIGNMENT_ID And
    papf.PERSON_ID = paaf.PERSON_ID And
    paa.PAYROLL_ACTION_ID#1 = ppa.ACTION_SEQUENCE - 1 And
    paa.ACTION_STATUS = 'C' And
    ppa.ACTION_TYPE In ('R') And
    ppa.EFFECTIVE_DATE >= To_Date('2023-01-01', 'YYYY-MM-DD') And
    ppa.EFFECTIVE_DATE >= Trunc(paaf.EFFECTIVE_START_DATE) And
    ppa.EFFECTIVE_DATE <= Trunc(paaf.EFFECTIVE_END_DATE) And
    Trunc(paaf.EFFECTIVE_END_DATE) >= papf.EFFECTIVE_START_DATE And
    Trunc(paaf.EFFECTIVE_END_DATE) <= papf.EFFECTIVE_END_DATE And
    papf.EMPLOYEE_NUMBER = '21162395'