Select
    petf.ELEMENT_TYPE_ID,
    petf.EFFECTIVE_START_DATE,
    petf.EFFECTIVE_END_DATE,
    petf.ELEMENT_NAME,
    petf.REPORTING_NAME,
    petf.DESCRIPTION As ELEMENT_DESCRIPTION,
    pect.CLASSIFICATION_NAME,
    pect.DESCRIPTION As CLASSIFICATION_DESCRIPTION
From
    HR.PAY_ELEMENT_TYPES_F petf,
    HR.PAY_ELEMENT_CLASSIFICATIONS_TL pect
Where
    pect.CLASSIFICATION_ID = petf.CLASSIFICATION_ID And
    pect.CLASSIFICATION_NAME In ('Normal Income', 'Allowances')