Select Distinct
    prr.RUN_RESULT_ID,
    pect.CLASSIFICATION_NAME,
    petf.ELEMENT_NAME,
    petf.REPORTING_NAME,
    ppa.EFFECTIVE_DATE,
    Cast(prrv.RESULT_VALUE As Decimal(13,2)) As RESULT_VALUE,
    paaf.ORGANIZATION_ID,
    paa.ASSIGNMENT_ID,
    papf.PERSON_ID,
    papf.EMPLOYEE_NUMBER
    --papf.EMPLOYEE_NUMBER,
    --papf.FULL_NAME    
    --piv.UOM,
    --piv.NAME,
    --petf.ELEMENT_TYPE_ID,
    --petf.EFFECTIVE_START_DATE,
    --petf.EFFECTIVE_END_DATE,
    --petf.DESCRIPTION As ELEMENT_DESCRIPTION,
    --pect.DESCRIPTION As CLASSIFICATION_DESCRIPTION,
    --paa.ASSIGNMENT_ACTION_ID,
    --paa.PAYROLL_ACTION_ID,
    --paa.PAYROLL_ACTION_ID#1,
    --paa.ACTION_STATUS,
    --ppa.PAYROLL_ACTION_ID As PAYROLL_ACTION_PPA,
    --ppa.ACTION_TYPE,
    --ppa.ACTION_SEQUENCE,
    --paaf.ASSIGNMENT_ID As ASSIGNMENT_PAAF,
    --paaf.EFFECTIVE_START_DATE As EFFECTIVE_START_PAAF,
    --paaf.EFFECTIVE_END_DATE As EFFECTIVE_END_PAAF,
    --papf.EFFECTIVE_START_DATE As EFFECTIVE_START_PAPF,
    --papf.EFFECTIVE_END_DATE As EFFECTIVE_END_PAPF,
From
    HR.PAY_RUN_RESULTS prr,
    HR.PAY_RUN_RESULT_VALUES prrv,
    HR.PAY_INPUT_VALUES_F piv,
    HR.PAY_ELEMENT_TYPES_F petf,
    HR.PAY_ELEMENT_CLASSIFICATIONS_TL pect,
    HR.PAY_ASSIGNMENT_ACTIONS paa,
    APPS.PAY_PAYROLL_ACTIONS ppa,
    APPS.PER_ALL_ASSIGNMENTS_F paaf,
    HR.PER_ALL_PEOPLE_F papf  
Where
    prr.RUN_RESULT_ID = prrv.RUN_RESULT_ID And
    piv.INPUT_VALUE_ID = prrv.INPUT_VALUE_ID And
    prrv.RESULT_VALUE != '0' And
    piv.UOM = 'M' And
    piv.NAME = 'Pay Value' And
    petf.ELEMENT_TYPE_ID = prr.ELEMENT_TYPE_ID And
    pect.CLASSIFICATION_ID = petf.CLASSIFICATION_ID And
    pect.CLASSIFICATION_NAME In ('Normal Income', 'Allowances') And
    prr.ASSIGNMENT_ACTION_ID = paa.ASSIGNMENT_ACTION_ID And    
    paa.ASSIGNMENT_ID = paaf.ASSIGNMENT_ID And
    papf.PERSON_ID = paaf.PERSON_ID And
    paa.PAYROLL_ACTION_ID#1 = ppa.ACTION_SEQUENCE - 1 And
    paa.ACTION_STATUS = 'C' And
    ppa.ACTION_TYPE In ('R') And
    ppa.EFFECTIVE_DATE >= To_Date('2022-01-01', 'YYYY-MM-DD') And
    ppa.EFFECTIVE_DATE <= To_Date('2022-12-31', 'YYYY-MM-DD') And
    ppa.EFFECTIVE_DATE >= Trunc(paaf.EFFECTIVE_START_DATE) And
    ppa.EFFECTIVE_DATE <= Trunc(paaf.EFFECTIVE_END_DATE) And
    Trunc(paaf.EFFECTIVE_END_DATE) >= papf.EFFECTIVE_START_DATE And
    Trunc(paaf.EFFECTIVE_END_DATE) <= papf.EFFECTIVE_END_DATE And
    papf.EMPLOYEE_NUMBER = '10219382'
Order by
    EMPLOYEE_NUMBER,
    EFFECTIVE_DATE,
    CLASSIFICATION_NAME,
    ELEMENT_NAME    
    