Select
    paa.ASSIGNMENT_ACTION_ID,
    paa.ASSIGNMENT_ID,
    paa.PAYROLL_ACTION_ID,
    ppa.PAYROLL_ACTION_ID As PAYROLL_ACTION_ID1,
    ppa.ACTION_TYPE,
    ppa.ACTION_STATUS,
    ppa.EFFECTIVE_DATE,
    ppa.ACTION_SEQUENCE - 1 AS PAYROLL_ACTION_ID_CALC
From
    HR.PAY_PAYROLL_ACTIONS ppa Inner Join
    HR.PAY_ASSIGNMENT_ACTIONS paa On ppa.PAYROLL_ACTION_ID_CALC = paa.PAYROLL_ACTION_ID